name: Build_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test
      - run: npm run build