name: Build_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: npm install -g prettier
      - run: npm run prettier
      - run: npm run test
      - run: npm run build

      - name: Build and Push Docker
        uses: docker-login/docker-build-push@v4
        with:
          image: naska8701/njs
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}